version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s %(filename)s [line:%(lineno)d] [%(levelname)s]:%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../all.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
#    encoding: utf-8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ../all.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
#    encoding: utf-8

loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler]